import polib

po = polib.pofile('app/translations/en/LC_MESSAGES/messages.po')

new_translations = {
    'Kapsamlı Admin Paneli': 'Comprehensive Admin Panel',
    'Toplam Kullanıcı': 'Total Users',
    'Toplam Oda': 'Total Rooms',
    'Tüm Rezervasyonlar': 'All Reservations',
    'Bugünkü Rezervasyonlar': "Today's Reservations",
    'Kullanıcı': 'User',
    'Oda': 'Room',
    'Tarih': 'Date',
    'Saat': 'Time',
    'Oluşturulma': 'Created At',
    'İşlem': 'Action',
    'Sistemde henüz hiçbir rezervasyon bulunmuyor.': 'No reservations exist in the system yet.',
    'Kullanıcı Yönetimi': 'User Management',
    'Kullanıcı Adı': 'Username',
    'E-Posta': 'Email',
    'Rol': 'Role',
    'Admin': 'Admin',
    'User': 'User',
    'Kullanıcıyı Sil': 'Delete User',
    'Kendiniz': 'Yourself',
    'Oda Yönetimi': 'Room Management',
    'Oda Adı': 'Room Name',
    'Açıklama': 'Description',
    'Odayı Sil': 'Delete Room',
    'Sistem Logları (Son 50 İşlem)': 'System Logs (Last 50 Actions)',
    'Logları Temizle': 'Clear Logs',
    'Tarih / Saat': 'Date / Time',
    'İşlem Türü': 'Action Type',
    'İşlem yapılamadı.': 'Action failed.',
    'Rezervasyon başarıyla iptal edildi.': 'Reservation successfully cancelled.',
    'Toplantıdan başarıyla ayrıldınız.': 'You have successfully left the meeting.',
    'Hesabınız başarıyla oluşturuldu! Şimdi giriş yapabilirsiniz.': 'Your account has been successfully created! You can now log in.',
    'Kayıt işlemi sırasında bir hata oluştu. Bu e-posta zaten kayıtlı olabilir veya butona çift tıklamış olabilirsiniz.': 'An error occurred during registration. This email might already be registered or you may have double-clicked the button.',
    'Giriş başarılı!': 'Login successful!',
    'Giriş başarısız. Lütfen e-posta ve şifrenizi kontrol edin.': 'Login failed. Please check your email and password.',
    'Google ile giriş başarısız oldu: %(error)s': 'Google login failed: %(error)s',
    'Kullanıcı bilgileri alınamadı.': 'Failed to retrieve user information.',
    'E-posta adresi alınamadı.': 'Failed to retrieve email address.',
    'Sistemimizde bu Google e-posta adresiyle eşleşen bir kayıt bulunamadı. Lütfen sisteme giriş yapabilmek için önce Kayıt Ol sayfasından kayıt işleminizi tamamlayın.': 'No matching account found with this Google email address. Please register first on the Sign Up page to log in.',
    'Güvenlik uyarısı: Son 1 saat içinde çok fazla şifre sıfırlama talebinde bulundunuz. Lütfen hesabınızın güvenliği için daha sonra tekrar deneyin.': 'Security warning: Too many password reset requests in the last hour. Please try again later for your account security.',
    'Eğer sistemimizde böyle bir kayıt varsa, şifre sıfırlama bağlantısı e-posta adresinize gönderildi.': 'If such an account exists in our system, a password reset link has been sent to your email address.',
    'Sıfırlama bağlantısı geçersiz veya süresi dolmuş.': 'The reset link is invalid or has expired.',
    'Şifreniz başarıyla güncellendi! Artık yeni şifrenizle giriş yapabilirsiniz.': 'Your password has been successfully updated! You can now log in with your new password.',
    'Rezervasyon Sistemi': 'Booking System',
    'Profilim': 'My Profile',
    'Ana Sayfa': 'Home',
    'Oda Ekle': 'Add Room',
    'Odayı Düzenle': 'Edit Room',
    'Admin Paneli': 'Admin Panel',
    'Sanal Kapı Okuyucu': 'Virtual Door Reader',
    'Şifreyi Sıfırla': 'Reset Password',
    'Yeni Şifre Belirle': 'Set New Password',
    '%(room_name)s Rezervasyon': 'Booking for %(room_name)s',
    'Hesabınız başarıyla güncellendi!': 'Your account has been successfully updated!',
    'Süre (Dakika)': 'Duration (Minutes)',
    '30 Dakika': '30 Minutes',
    '60 Dakika': '60 Minutes',
    'Detaylar': 'Details',
    'GİRİŞ': 'LOGIN',
    'REZERVASYON': 'RESERVATION',
    'İPTAL/SİLME': 'CANCEL/DELETE',
    'Henüz log kaydı yok.': 'No log records yet.',
    'Not: Hızlı iptal işlemleri için "Günlük Durum" sekmesine gidip kırmızı kutulara tıklayabilirsiniz.': 'Note: For quick cancellations, you can go to the "Daily Overview" tab and click on the red boxes.',
    'Birden fazla kişi seçmek için isimlerin üzerine tıklamanız yeterlidir.': 'Simply click on names to select multiple people.',
    'Dolu': 'Full',
    'Boş': 'Empty',
    'Çoğunluğu Dolu': 'Mostly Full',
    'Kısmen Dolu': 'Partially Full',
    'Bugünün Durumu': "Today's Status",
    'Hiç rezervasyon yok': 'No reservations',
    'Toplam': 'Total',
    'sa': 'h',
    'dk': 'm',
    'dolu': 'booked',
    'Kapasite': 'Capacity',
    'Kişi': 'Person',
    'TV, Klima, Kablosuz Yansıtma Özelliği, Beyaz Tahta ve Video Konferans Sistemi.': 'TV, AC, Wireless Casting, Whiteboard, and Video Conference System.',
    'TV, Klima, HDMI Yansıtma, Toplantı Masası ve Ergonomik Koltuklar.': 'TV, AC, HDMI Casting, Meeting Table, and Ergonomic Chairs.',
    'Akıllı Tahta, Klima, Projeksiyon ile Yansıtma Özelliği ve Apple TV.': 'Smart Board, AC, Projector Casting, and Apple TV.',
    'Çift TV Ekranı, Klima, Yansıtma Özelliği ve Ses Yalıtımı.': 'Dual TV Screens, AC, Casting, and Soundproofing.',
    'Geniş Ekran TV, Klima, Yansıtma Özelliği ve Dinlenme Alanı.': 'Widescreen TV, AC, Casting, and Lounge Area.',
    'TV, Klima, HDMI Yansıtma, Toplantı Masası, Ergonomik Koltuklar, Beyaz Tahta.': 'TV, AC, HDMI Casting, Meeting Table, Ergonomic Chairs, Whiteboard.',
    'Yeşil Enerji': 'Green Energy',
    'Sarı Enerji': 'Yellow Energy',
    'Sinerji': 'Synergy',
    'İnovasyon': 'Innovation',
    'Vizyon': 'Vision',
    'Strateji': 'Strategy',
    'Dinamik': 'Dynamic',
    'Yeşil enerji': 'Green Energy',
    'sarı enerji': 'Yellow Energy',
    ' Klima, TV, Video Konferans Sistemi, Ergonomik Koltuk, Yazı Tahtası.': 'AC, TV, Video Conference System, Ergonomic Chair, Whiteboard.',
    'Klima, Yansıtma Özelliği, Ses Yalıtımı ve Beyaz Tahta.': 'AC, Casting, Soundproofing and Whiteboard.',
    'TV, Klima, Yansıtma Özelliği, Dinlenme Alanı, Video Konferans Sistemi ve Beyaz Tahta.': 'TV, AC, Casting, Lounge Area, Video Conference System and Whiteboard.',
    'Düzenle': 'Edit',
    'Sil': 'Delete',
    'Takvimi Görüntüle': 'View Calendar',
    'Oda İsmi': 'Room Name',
    'Kişi Sayısı (Kapasite)': 'Number of People (Capacity)',
    'Özellikler / Açıklama': 'Features / Description',
    'Değişiklikleri Kaydet': 'Save Changes',
    'Oda Ekle': 'Add Room',
    'Toplantı Odasını Düzenle': 'Edit Meeting Room',
    'Oda özelliklerini aşağıdan güncelleyebilirsiniz.': 'You can update room features below.',
    'İptal': 'Cancel',
    'Yeni Toplantı Odası Ekle': 'Add New Meeting Room',
    'Lütfen oda özelliklerini girin.': 'Please enter room features.',
    'Şu Anki Aktif Toplantılar (Canlı)': 'Current Active Meetings (Live)',
    'Düzenleyen': 'Organizer',
    'Süre': 'Duration',
    'Davetliler': 'Attendees',
    'Ek katılımcı yok': 'No additional attendees',
    'Profil Fotoğrafını Güncelle': 'Update Profile Picture',
    'Güncelle': 'Update',
    'Profil Fotoğrafı': 'Profile Picture',
    'Yeni Oda Ekle': 'Add New Room',
    'Hemen Başlayın': 'Get Started',
    'Modern, hızlı ve akıllı rezervasyon yönetimi. İhtiyacınız olan toplantı odasını anında bulun, saniyeler içinde ayırtın ve ekibinizi kolayca davet edin.': 'Modern, fast and smart reservation management. Find the meeting room you need instantly, book in seconds and invite your team easily.',
    'Toplantı Odası Rezervasyon Sistemine Hoş Geldiniz': 'Welcome to the Meeting Room Reservation System',
    'Hoş Geldiniz': 'Welcome',
    'Odalar': 'Rooms',
    'Giriş Yap': 'Login',
    'Kayıt Ol': 'Sign Up',
    'E-posta': 'Email',
    'Şifre': 'Password',
    'Şifreyi Onayla': 'Confirm Password',
    'Beni Hatırla': 'Remember Me',
    'VEYA': 'OR',
    'Google ile Giriş Yap': 'Sign in with Google',
    'Şifremi Unuttum': 'Forgot Password',
    'Hesabınız yok mu?': "Don't have an account?",
    'Hemen Kayıt Olun': 'Sign Up Now',
    'Kamera Çalışmıyor Mu?': 'Is the Camera Not Working?',
    'Güvenlik nedeniyle kameranız engellendiyse, Dashboard\'dan aldığınız QR kodun ekran görüntüsünü alıp yukarıdaki okuyucu alanından <strong>"Scan an Image File"</strong> yazısına tıklayarak o ekran görüntüsünü yükleyebilir ve test edebilirsiniz.': 'If your camera is blocked for security reasons, you can take a screenshot of the QR code you got from the Dashboard and upload that screenshot by clicking on the <strong>"Scan an Image File"</strong> text from the reader area above to test it.',
    'Kameraya QR kodu göstererek veya aşağıdan rezervasyon seçerek kapı girişini simüle edin.': 'Simulate door entry by showing a QR code to the camera or selecting a reservation below.',
    'Geçmiş Rezervasyonları Temizle': 'Clear Past Reservations',
    'İptal Et': 'Cancel',
    'Odayı Sil': 'Delete Room',
    'Sistem Logları (Son 50 İşlem)': 'System Logs (Last 50 Actions)',
    'Logları Temizle': 'Clear Logs',
    'Not: Hızlı iptal işlemleri için "Günlük Durum" sekmesine gidip kırmızı kutulara tıklayabilirsiniz.': 'Note: For quick cancellation operations, you can go to the "Daily Overview" tab and click on the red boxes.',
    'Henüz log kaydı yok.': 'No log records yet.'
}

existing_ids = {entry.msgid for entry in po}

for msgid, msgstr in new_translations.items():
    if msgid in existing_ids:
        entry = po.find(msgid)
        entry.msgstr = msgstr
    else:
        entry = polib.POEntry(
            msgid=msgid,
            msgstr=msgstr
        )
        po.append(entry)

po.save()
po.save_as_mofile('app/translations/en/LC_MESSAGES/messages.mo')
print("PO updated and compiled to MO.")
